### ISSUE TITLE
Run shieldhit from backend

### ISSUE THREAD

**Issue by retkiewi** [yaptide/yaptide#43]

**Comment by grzanka** [comment]
See PR here https://github.com/DataMedSci/pymchelper/pull/185

**Comment by grzanka** [comment]
We assume that backend receives some REST request which triggers SH12A calculation.
As a response JSON with simulation results (list of numbers?) is being sent.
This requires adding new dependency into requirements.txt - pymchelper package

**Comment by grzanka** [comment]
Note that full `shieldhit` binary is not shipped with `pymchelper`, we can rely on demo version,.

**Comment by grzanka** [comment]
Automated tests should be added as well.

**Comment by grzanka** [comment]
Basic implementation was added in PR #78
