### ISSUE TITLE
regressing back to single repository

### ISSUE THREAD

**Issue by wkozyra95** [yaptide/yaptide#5]

**Comment by wkozyra95** [comment]
monorepo
Pros:
- easier to introduce changes
- simplification of build system
- easier versioning
- easier to setup dev environment/build tools/code reloading

Cons:
- make it easier to create tighter couplings in a codebase
- large dependency for any potential project (minor issue)
- long build time on ci
- harder to build frontend and backend in one docker or ci environment
- (from @zagura) it's harder to mark stable versions of converter 

@Slayyy 
@zagura 
@Sewerinius 
any thoughts about this?

**Comment by slsyy** [comment]
For go apps: app and worker we can merge all repos using this layout: https://medium.com/golang-learn/go-project-layout-e5213cdcfaa2 .
I'm not sure how we want to tie backend and frontend, cause they should be seperated. One option is to use frontend from yaptide/app using git submodule. This approach seperate CI builds, and allows easy development.

**Comment by wkozyra95** [comment]
if we decide to merge repos i was intending to leave fronted as separate and if it will come to writing frontend in go it would be in one repo

as for ci is not very effective solution to use submodules because it would require as to bump submodule commit hash every time we deploying

**Comment by wkozyra95** [comment]
Conclusions
Separation of repositories forced us to decouple parts of application and that had positive effect on improving code structure but i think cost of maintaining own custom build tool and syncing converter and app versions is to large.

- we will still use converter as separate library (but in the same repo)
- travis seems to have good support form multi language apps now
- with gopkg.in we can still use shorter url even if we have yaptide/yaptide repo
- with prepush hooks to git rebuilding everything on ci won't be a problem because it will check first locally
- repo will be renamed to github.com/yaptide/yaptide
- imports inside package will be changed to gopkg.in/yaptide
